apiVersion: v1
kind: Service
metadata:
  name: rickygitopsdeploy
  namespace: namespace-workflow-1733304048601
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: rickygitopsdeploy
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000